config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'maps#global'
  resources :structures, only: [:index, :show]
  resources :references, only: [:index, :show]
  resources :individuals, only: [:index, :show]
  resources :projects, only: [:index, :show]
  get '/map_structures', to: 'structures#map'
  get '/map_projects', to: 'projects#map'
  get '/global_map', to: 'maps#global'
  resources :partners, only: [:index]
  get '/about', to: 'statics#about'

  namespace :admin do
	  resources :structures
	  resources :structure_types, only: [:create, :new, :edit, :update, :destroy]
	  resources :structure_classifications, only: [:new, :create, :edit, :update, :destroy]
	  resources :structure_relations, only: [:create, :new, :destroy]
	  resources :parent_child_relations, only: [:new, :create, :destroy]
	  resources :references
    resources :reference_classes, only: [:new, :create, :edit, :update, :destroy]
	  resources :individuals
    resources :partners, only: [:new, :create, :edit, :update, :destroy]
    resources :structure_partners, only: [:new, :create, :destroy]
    resources :projects
    resources :project_classes, only: [:new, :create, :edit, :update, :destroy]
    resources :project_project_classes, only: [:create, :destroy]
    resources :partner_projects, only: [:create, :destroy]
    resources :structure_projects, only: [:create, :destroy]
  end
end

app/models/structure.rb
class Structure < ApplicationRecord
	include Geokit::Geocoders

	after_create :get_lat_lng

	belongs_to :structure_type
	belongs_to :structure_classification

	has_many :structure_individuals
	has_many :individuals, through: :structure_individuals

	has_many :is_parent, foreign_key: "parent_id", class_name: "ParentChildRelation"
	has_many :is_child, foreign_key: "child_id", class_name: "ParentChildRelation"
	has_many :child_structures, through: :is_parent, source: :child
	has_many :parent_structures, through: :is_child, source: :parent

	has_many :is_supported, foreign_key: "supported_id", class_name: "StructureRelation"
	has_many :is_supported_by, through: :is_supported, source: :supporting
	has_many :supports_structures, foreign_key: "supporting_id", class_name: "StructureRelation"
	has_many :supports, through: :supports_structures, source: :supported

	has_many :structure_partners
	has_many :partners, through: :structure_partners

	has_many :structure_projects
	has_many :projects, through: :structure_projects

	has_one :association_detail

	enum status: {player: "0", partner: "1", both: "2"}

	enum public: {large_public: "0", professional: "1", for_all: "2"}

	acts_as_mappable :default_units => :kms,
                   :default_formula => :sphere,
                   :distance_field_name => :distance,
                   :lat_column_name => :lat,
                   :lng_column_name => :lng

	def status_fr
		if self.status == "player"
			return "Acteur"
		elsif self.status == "partner"
			return "Partenaire"
		else
			return "Acteur & Partenaire"
		end
	end

	def public_fr
		if self.public == "large_public"
			return "Grand Public"
		elsif self.public == "professional"
			return "Professionnel"
		else
			return "Grand public & Professionnel"
		end
	end

	def active?
		if self.active == true
			return "Actif"
		else
			return "Non Actif"
		end
	end

	def full_address
		if self.address != "" && self.zip_code != "" && self.city != "" && self.country != ""
			return self.address + ", " + self.zip_code + ", " +  self.city + ", " + self.country
		elsif self.address == "" && self.zip_code != "" && self.city != "" && self.country != ""
			return self.zip_code + ", " +  self.city + ", " + self.country
		elsif self.address == "" && self.zip_code == "" && self.city != "" && self.country != ""
			return self.city + ", " + self.country
		elsif self.address == "" && self.zip_code == "" && self.city == "" && self.country != ""
			return self.country
		end
	end

	def get_lat_lng
		full_address = self.address + ", " + self.zip_code + ", " +  self.city + ", " + self.country
		loc = Geokit::Geocoders::GoogleGeocoder.geocode(full_address)
		if loc.success
			self.update(lat: loc.lat, lng: loc.lng)
		end
	end

	def array_partners
		array_partners = []
		self.partners.each do |partner|
			array_partners << partner.name
		end
		return array_partners
	end

end

app/models/structure_type.rb
class StructureType < ApplicationRecord
	has_many :structures
end

app/controllers/admin/structures_controller.rb
class Admin::StructuresController < ApplicationController
  before_action :set_variables
  before_action :is_admin, only: [:new, :create, :edit, :update, :destroy]

  def index
    @structures = Structure.all.order("name ASC")
  end

  def show
    @structure = Structure.find(params[:id])
    @structure_type = StructureType.find(@structure.structure_type_id)
    @structure_classification = StructureClassification.find(@structure.structure_classification_id)
  end

  def new
  end

  def create
    if params[:active] == "true"
      params[:active] = true
    else
      params[:active] = false
    end
    @structure = Structure.create(structure_type_id: params[:structure_type_id], structure_classification_id: params[:structure_classification_id], name: params[:name], description: params[:description], address: params[:address], zip_code: params[:zip_code], city: params[:city], country: params[:country], telephone: params[:telephone], email: params[:email], website: "http://" + params[:website], facebook: "http://" + params[:facebook], twitter: "http://" + params[:twitter], instagram: "http://" + params[:instagram], creation: params[:creation], staff_number: params[:staff_number], status: params[:status], notes: params[:notes], public: params[:public], active: params[:active])
    if params[:association_details] == "1"
      AssociationDetail.create(structure_id: @structure.id, supporters_amount: params[:number_supporters].to_i, object: params[:object])
    end
    redirect_to admin_structure_path(@structure.id)
  end

  def edit
    @structure = Structure.find(params[:id])
    @selected_structure_type = [StructureType.find(@structure.structure_type_id).name, @structure.structure_type_id]
    @selected_structure_classification = [StructureClassification.find(@structure.structure_classification_id).name, @structure.structure_classification_id]
  end

  def update
    if params[:active] == "true"
      params[:active] = true
    else
      params[:active] = false
    end
    @structure = Structure.find(params[:id])
    if params[:status] == "3" && params[:active] == "3" && params[:public] == "3"
      @structure.update(structure_type_id: params[:structure_type_id], structure_classification_id: params[:structure_classification_id], name: params[:name], description: params[:description], address: params[:address], zip_code: params[:zip_code], city: params[:city], country: params[:country], telephone: params[:telephone], email: params[:email], website: "http://" + params[:website], facebook: "http://" + params[:facebook], twitter: "http://" + params[:twitter], instagram: "http://" + params[:instagram], creation: params[:creation], staff_number: params[:staff_number], notes: params[:notes])
    elsif params[:status] == "3" && params[:active] == "3" && params[:public] != "3"
      @structure.update(structure_type_id: params[:structure_type_id], structure_classification_id: params[:structure_classification_id], name: params[:name], description: params[:description], address: params[:address], zip_code: params[:zip_code], city: params[:city], country: params[:country], telephone: params[:telephone], email: params[:email], website: "http://" + params[:website], facebook: "http://" + params[:facebook], twitter: "http://" + params[:twitter], instagram: "http://" + params[:instagram], creation: params[:creation], staff_number: params[:staff_number], notes: params[:notes], public: params[:public])
    elsif params[:status] == "3" && params[:active] != "3" && params[:public] != "3"
      @structure.update(structure_type_id: params[:structure_type_id], structure_classification_id: params[:structure_classification_id], name: params[:name], description: params[:description], address: params[:address], zip_code: params[:zip_code], city: params[:city], country: params[:country], telephone: params[:telephone], email: params[:email], website: "http://" + params[:website], facebook: "http://" + params[:facebook], twitter: "http://" + params[:twitter], instagram: "http://" + params[:instagram], creation: params[:creation], staff_number: params[:staff_number], notes: params[:notes], public: params[:public], active: params[:active])
    elsif params[:status] == "3" && params[:active] != "3" && params[:public] == "3"
      @structure.update(structure_type_id: params[:structure_type_id], structure_classification_id: params[:structure_classification_id], name: params[:name], description: params[:description], address: params[:address], zip_code: params[:zip_code], city: params[:city], country: params[:country], telephone: params[:telephone], email: params[:email], website: "http://" + params[:website], facebook: "http://" + params[:facebook], twitter: "http://" + params[:twitter], instagram: "http://" + params[:instagram], creation: params[:creation], staff_number: params[:staff_number], notes: params[:notes], active: params[:active])
    elsif params[:status] != "3" && params[:active] != "3" && params[:public] == "3"
      @structure.update(structure_type_id: params[:structure_type_id], structure_classification_id: params[:structure_classification_id], name: params[:name], description: params[:description], address: params[:address], zip_code: params[:zip_code], city: params[:city], country: params[:country], telephone: params[:telephone], email: params[:email], website: "http://" + params[:website], facebook: "http://" + params[:facebook], twitter: "http://" + params[:twitter], instagram: "http://" + params[:instagram], creation: params[:creation], staff_number: params[:staff_number], status: params[:status], notes: params[:notes], active: params[:active])
    elsif params[:status] != "3" && params[:active] == "3" && params[:public] == "3"
      @structure.update(structure_type_id: params[:structure_type_id], structure_classification_id: params[:structure_classification_id], name: params[:name], description: params[:description], address: params[:address], zip_code: params[:zip_code], city: params[:city], country: params[:country], telephone: params[:telephone], email: params[:email], website: "http://" + params[:website], facebook: "http://" + params[:facebook], twitter: "http://" + params[:twitter], instagram: "http://" + params[:instagram], creation: params[:creation], staff_number: params[:staff_number], status: params[:status], notes: params[:notes])

    else
      @structure.update(structure_type_id: params[:structure_type_id], structure_classification_id: params[:structure_classification_id], name: params[:name], description: params[:description], address: params[:address], zip_code: params[:zip_code], city: params[:city], country: params[:country], telephone: params[:telephone], email: params[:email], website: "http://" + params[:website], facebook: "http://" + params[:facebook], twitter: "http://" + params[:twitter], instagram: "http://" + params[:instagram], creation: params[:creation], staff_number: params[:staff_number], status: params[:status], notes: params[:notes], public: params[:public], active: params[:active])
    end

    if @structure.association_detail
      association_details = AssociationDetail.find(@structure.association_detail.id)
      association_details.update(object: params[:object], supporters_amount: params[:number_supporters].to_i)
    end

    @structure.get_lat_lng
    
    redirect_to admin_structure_path(@structure.id)
  end

  def destroy
    @structure = Structure.find(params[:id])
    @structure.destroy
    redirect_to admin_structures_path
  end

  private

  def set_variables
    @structure_types = []
    StructureType.all.order("name ASC").each do |structure_type|
      @structure_types << [structure_type.name, structure_type.id]
    end

    @structure_classifications = []
    StructureClassification.all.order("name ASC").each do |structure_classification|
      @structure_classifications << [structure_classification.name, structure_classification.id]
    end
  end
end

app/controllers/structures_controller.rb
class StructuresController < ApplicationController
  before_action :set_variables

  def index
    @structures_count = Structure.all.count
    @structures_types.insert(0, ["Tous les types de structures", 0])
    @structures_classifications.insert(0, ["Tous les classifications de structures", 0])

    case
      when (params[:search] == " " || params[:search] == "") && params[:structure_type_id] == "0" && params[:structure_classification_id] == "0"
        @structures = Structure.all.order("name ASC")

      when params[:search] && params[:structure_type_id] == "0" && params[:structure_classification_id] == "0"
        @structures = Structure.where('lower(name) LIKE ?', "%#{params[:search].downcase}%") + Structure.where('lower(city) LIKE ?', "%#{params[:search].downcase}%")

      when params[:search] && params[:search] != "" && params[:search] != " " && (params[:structure_type_id] != "0" || params[:structure_classification_id] != "0")
        @structures = []
        @structures_search = Structure.where('lower(name) LIKE ?', "%#{params[:search].downcase}%") + Structure.where('lower(city) LIKE ?', "%#{params[:search].downcase}%")
        
        if params[:structure_type_id] != "0" && params[:structure_classification_id] == "0"
          @structures_search.each do |structure|
            if structure.structure_type_id == params[:structure_type_id].to_i
              @structures << structure
            end
          end
        end
        
        if params[:structure_classification_id] != "0" && params[:structure_type_id] == "0"
          @structures_search.each do |structure|
            if structure.structure_classification_id == params[:structure_classification_id].to_i
              @structures << structure
            end
          end
        end

        if params[:structure_type_id] != "0" && params[:structure_classification_id] != "0"
          @structures_search_type = []
          @structures_search.each do |structure|
            if structure.structure_type_id == params[:structure_type_id].to_i
              @structures_search_type << structure
            end
          end
          @structures_search_type.each do |structure|
            if structure.structure_classification_id == params[:structure_classification_id].to_i
              @structures << structure
            end
          end
        end

      when (params[:search] == " " || params[:search] == "") && (params[:structure_type_id] != "0" || params[:structure_classification_id] != "0")
        @structures = []

        if params[:structure_type_id] != "0" && params[:structure_classification_id] == "0"
          Structure.all.each do |structure|
            if structure.structure_type_id == params[:structure_type_id].to_i
              @structures << structure
            end
          end
        end
        
        if params[:structure_classification_id] != "0" && params[:structure_type_id] == "0"
          Structure.all.each do |structure|
            if structure.structure_classification_id == params[:structure_classification_id].to_i
              @structures << structure
            end
          end
        end

        if params[:structure_type_id] != "0" && params[:structure_classification_id] != "0"
          @structures_search_type = []
          Structure.all.each do |structure|
            if structure.structure_type_id == params[:structure_type_id].to_i
              @structures_search_type << structure
            end
          end
          @structures_search_type.each do |structure|
            if structure.structure_classification_id == params[:structure_classification_id].to_i
              @structures << structure
            end
          end
        end
        
      else
         @structures = Structure.all.order("name ASC")
    end

    if params[:structure_type_id].to_i != 0
      @structure_type = StructureType.find(params[:structure_type_id].to_i)
      @selected_structures_type = [@structure_type.name, @structure_type.id]
    end

    if params[:structure_classification_id].to_i != 0
      @structure_classification = StructureClassification.find(params[:structure_classification_id].to_i)
      @selected_structures_classification = [@structure_classification.name, @structure_classification.id]
    end

  end

  def show
    @structure = Structure.find(params[:id])
    @structure_type = StructureType.find(@structure.structure_type_id)
    @structure_classification = StructureClassification.find(@structure.structure_classification_id)
  end

  def map
  	@structures = Structure.all.order("name ASC")
  end

  private

  def set_variables
    @structures_types = []
    StructureType.all.each do |structure_type|
      @structures_types << [structure_type.name, structure_type.id]
    end

    @structures_classifications = []
    StructureClassification.all.each do |structure_classification|
      @structures_classifications << [structure_classification.name, structure_classification.id]
    end
  end
end

app/helpers/structures_helper.rb
module StructuresHelper
end

app/views/structures/index.html.erb
<div class="container-sidebar-wrapper">

	<%= render 'layouts/sidebar_user' if !user_signed_in? %>

	<div id="content">

		<div class="row justify-content-center">

			<div class="col-xl-8 col-lg-10 col-md-12" style="margin-top: 8vh; margin-bottom: 8vh">

				<h3>Structures</h3>

				<%= form_tag url_for(action: 'index'), method: :get do %>
				<div class="form-group">
					<%= text_field_tag :search, params[:search], :placeholder => "Rechercher parmi les structures", :class => "form-control" %>
				</div>

				<div class="row form-group" style="margin-top: -6px">
					<div class="col-6">
					<%= select_tag(:structure_type_id, options_for_select(@structures_types, @selected_structures_type), :class => "custom-select my-1 mr-sm-2") %>
					</div>
					<div class="col-6">
					<%= select_tag(:structure_classification_id, options_for_select(@structures_classifications, @selected_structures_classification), :class => "custom-select my-1 mr-sm-2") %>
					</div>
				</div>

				<div class="form-group" style="margin-top: -6px">
					<%= submit_tag "Rechercher", :class => "btn btn-lg btn-sm btn-block btn-dark" %>
				</div>
				<% end %>

				<br/>
				
				<% if (params[:structure_type_id].to_i != 0 || params[:structure_classification_id].to_i != 0) || (params[:search] && params[:search] != "" && params[:search] != " ") %>
				<p class="small"><b><%= @structures.count %>
					<% if @structures.count <= 1 %>
					structure correspondant à votre recherche.
					<% else %>
					structures correspondent à votre recherche.
					<% end %>
				</b></p>
				<% else %>
				<p class="small"><b><span class="count"><%= @structures_count %></span> structures référencées sur Matière.</b></p>
				<% end %>

				<% if @structures.count > 0 %>

				<div class="card">
				  <ul class="list-group list-group-flush">
				  	<% @structures.each do |structure| %>
						<li class="list-group-item align-items-center">
							<% if structure.status == "player" %>
							<i class="fas fa-users"></i>
							<% elsif structure.status == "partner" %>
							<i class="fas fa-hands-helping"></i>
							<% else %>
							<i class="fas fa-users"></i> <i class="fas fa-hands-helping"></i>
							<% end %>
							<%= link_to structure.name, structure_path(structure.id) %>
							<br/><span class="small"><%= structure.city %> | <%= StructureType.find(structure.structure_type_id).name %> | <%= StructureClassification.find(structure.structure_classification_id).name %></span>
							<% if structure.creation != nil %>
							<span class="float-right small">créé en <%= structure.creation %></span>
							<% end %>
						</li>
					<% end %>
				  </ul>
				</div>

				<% end %>
				
			</div>
		</div>
		<%= render 'layouts/footer' %>
	</div>
</div>

<script type="text/javascript">
	$('.count').each(function () {
        $(this).prop('Counter',0).animate({
            Counter: $(this).text()
        }, {
            duration: 4000,
            easing: 'swing',
            step: function (now) {
                $(this).text(Math.ceil(now));
            }
        });
    });
</script>

app/views/structures/map.html.erb
<div class="container-sidebar-wrapper">

	<%= render 'layouts/sidebar_user' if !user_signed_in? %>

	<div id="map-content">
		<div id="mapid" style="height: 100vh; width: 100%;">
		</div>
	</div>

</div>

<script type="text/javascript">

	var mymap = L.map('mapid').setView([46.803178243429265,2.735502332685428], 6);
	L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token={accessToken}', {
	attribution: '© <a href="https://www.mapbox.com/about/maps/">Mapbox</a> © <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>',
	tileSize: 512,
	maxZoom: 18,
	zoomOffset: -1,
	id: 'mapbox/light-v10',
	accessToken: 'pk.eyJ1IjoiYXZuZDI2IiwiYSI6ImNqdXUwamMwNTBjcDA0YW52ODM1Nnp5OW4ifQ.X2B60gqbpNhbYZvIkhsZRg'
	}).addTo(mymap);

	<% @structures.each do |structure| %>

		var <%= "marker" + structure.id.to_s %> = L.marker([<%= structure.lat.to_s + ", " + structure.lng.to_s %>]).addTo(mymap);

		var <%= "container" + structure.id.to_s %> = $('<div />');

		<%= "container" + structure.id.to_s %>.on('click', '.smallPolygonLink', function() {});

		<%= "container" + structure.id.to_s %>.html("<a href='<%= structure_path(structure.id) %>' class='smallPolygonLink'><%= structure.name %></a><br/>");
		<%= "container" + structure.id.to_s %>.append($('<span class="bold">').text(" <%= StructureClassification.find(structure.structure_classification_id).name %> | <%= StructureType.find(structure.structure_type_id).name %>"))

		<%= "marker" + structure.id.to_s %>.bindPopup(<%= "container" + structure.id.to_s %>[0]);
	<% end %>
  </script>

app/views/structures/show.html.erb
<div class="container-sidebar-wrapper">

	<%= render 'layouts/sidebar_user' if !user_signed_in? %>

	<div id="content">
		<div class="row justify-content-center">
			<div class="col-xl-8 col-lg-10 col-md-12" style="margin-top: 8vh; margin-bottom: 8vh">

				<%= link_to structures_path do %>
					<p class="small"><i class="fas fa-arrow-left"></i> Retour à la liste des structures</p>
					<% end %>
					<br>

				<div class="card">
				  <div class="card-body">
				    <h2 class="card-title"><b><%= @structure.name %></b></h2>
				    <span class="badge badge-secondary"><%= @structure_classification.name %></span><br>
				    <span class="badge badge-info"><%= @structure_type.name %></span><br>
					<span class="badge badge-light"><%= @structure.status_fr %></span> <span class="badge badge-light"><%= @structure.public_fr %></span> <span class="badge badge-light"><%= @structure.active? %></span>
					<% if @structure.creation != nil %>
				   	<span class="float-right">Créé en <%= @structure.creation %></span>
				   	<% end %>
				  </div>
				  <ul class="list-group list-group-flush">
				  	<li class="list-group-item"><b>Description</b> : 
				  		<% if @structure.description != "" %>
				  		<%= break_the_lines(@structure.description) %>
				  		<% else %>
				  		<i>non informée</i>
				  		<% end %>
				  	</li>
				  	<% if @structure.staff_number != nil %>
				  	<li class="list-group-item"><b>Nombre d'employés / de membres actifs</b> : <%= @structure.staff_number %></li>
				  	<% end %>
				  	<% if @structure.full_address != "" %>
				    <li class="list-group-item"><b>Adresse</b> : <%= @structure.full_address %></li>
				    <% end %>
				    <li class="list-group-item"><b>Email</b> : 
				    	<% if @structure.email != "" %>
				    	<%= link_to @structure.email, "mailto:#{@structure.email}" %>
				    	<% else %>
				    	<i>non informé</i>
				    	<% end %>

				    	<% if @structure.telephone != "" %>
				    	<span class="float-right">Telephone : <%= @structure.telephone %></span>
				    	<% end %>
				    </li>
				    <li class="list-group-item"><b>Site internet</b> : 
				    	<% if @structure.website != "http://" %>
				    	<a href="<%= @structure.website %>" target="_blank"><%= @structure.website %></a>
				    	<% else %>
				    	<i>non informé</i>
				    	<% end %>
				    	<span class="float-right">
				    		<% if @structure.facebook != "http://" %>
				    			<a href="<%= @structure.facebook %>" target="_blank">
				    			<i class="fab fa-facebook-f"></i></a> &nbsp;&nbsp;&nbsp;
				    		<% end %>
				    		<% if @structure.twitter != "http://" %>
				    			<a href="<%= @structure.twitter %>" target="_blank">
				    			<i class="fab fa-twitter"></i></a> &nbsp;&nbsp;&nbsp;
				    		<% end %>
				    		<% if @structure.instagram != "http://" %>
				    			<a href="<%= @structure.instagram %>" target="_blank">
				    			<i class="fab fa-instagram"></i></a>
				    		<% end %>
				    	</span>
				    </li>
				    <% if @structure.partners != [] %>
				    <li class="list-group-item">
				    	<% if @structure.partners.count == 1 %>
				    		<b>Est soutenu par le partenaire</b> : 
				    	<% else %>
				    		<b>Est soutenu par les partenaires</b> :
				    	<% end %>
				    	<% i = 1 %>
				    	<% @structure.partners.each do |partner| %>
				    		<%= link_to partner.name, partner.website, target: "_blank" %><% if @structure.partners.count > 1 && i != @structure.partners.count %>, <% end %>
				    		<% i += 1 %>
				    	<% end %>
				    </li>
				    <% end %>
				    <% if @structure.is_supported_by != [] %>
				    <li class="list-group-item">
				    	<% if @structure.is_supported_by.count == 1 %>
				    		<b>Est soutenu par la structure</b> : 
				    	<% else %>
				    		<b>Est soutenu par les structures</b> : 
				    	<% end %>

				    	<% j = 1 %>
				    	<% @structure.is_supported_by.each do |support| %>
				    		<%= link_to support.name, structure_path(support.id) %><% if @structure.is_supported_by.count > 1 && j != @structure.is_supported_by.count %>, <% end %>
				    		<% j += 1 %>
				    	<% end %>
				    </li>
				    <% end %>
				    <% if @structure.supports != [] %>
				    <li class="list-group-item">
				    	<% if @structure.supports.count == 1 %>
				    		<b>Soutient la structure suivante</b> : 
				    	<% else %>
				    		<b>Soutient les structures suivantes</b> : 
				    	<% end %>

				    	<% k = 1 %>
				    	<% @structure.supports.each do |support| %>
				    		<%= link_to support.name, structure_path(support.id) %><% if @structure.supports.count > 1 && k != @structure.supports.count %>, <% end %>
				    		<% k += 1 %>
				    	<% end %>
				    </li>
				    <% end %>
				    <% if @structure.child_structures != [] %>
				    <li class="list-group-item">
				    	<b>Est parent de</b> : 
				    	<% l = 1 %>
				    	<% @structure.child_structures.each do |child| %>
				    		<%= link_to child.name, structure_path(child.id) %><% if @structure.child_structures.count > 1 && l != @structure.child_structures.count %>, <% end %>
				    		<% l += 1 %>
				    	<% end %>
				    </li>
				    <% end %>
				    <% if @structure.parent_structures != [] %>
				    <li class="list-group-item">
				    	<b>Est enfant de</b> : 
				    	<% m = 1 %>
				    	<% @structure.parent_structures.each do |parent| %>
				    		<%= link_to parent.name, structure_path(parent.id) %><% if @structure.parent_structures.count > 1 && m != @structure.parent_structures.count %>, <% end %>
				    		<% m += 1 %>
				    	<% end %>
				    </li>
				    <% end %>
				  </ul>
				</div>

				<% if @structure.individuals.count > 0 %>
				<div class="card" style="margin-top: 30px">
					<div class="card-body">
						<% if @structure.individuals.count == 1 %>
						<h5 class="card-title">Personne associée</h5>
						<% else %>
						<h5 class="card-title">Personnes associées</h5>
						<% end %>
					</div>
					<ul class="list-group list-group-flush">
						<% @structure.individuals.each do |individual| %>
				  		<li class="list-group-item"> <%= link_to individual.first_name.capitalize + " " + individual.last_name.upcase, individual_path(individual.id) %> </li>
				  		<% end %>
				  	</ul>
				</div>
				<% end %>

				<% if @structure.projects.count > 0 %>
				<div class="card" style="margin-top: 30px">
					<div class="card-body">
						<% if @structure.projects.count == 1 %>
						<h5 class="card-title">Projet de <%= @structure.name %></h5>
						<% else %>
						<h5 class="card-title">Projets de <%= @structure.name %></h5>
						<% end %>
					</div>
					<ul class="list-group list-group-flush">
						<% @structure.projects.each do |project| %>
				  		<li class="list-group-item"> <%= link_to project.title, project_path(project.id) %> </li>
				  		<% end %>
				  	</ul>
				</div>
				<% end %>

				<% if @structure.association_detail %>
				<div class="card" style="margin-top: 30px">
					<div class="card-body">
						<h5 class="card-title">Détails de l'association</h5>
					</div>
					<ul class="list-group list-group-flush">
						<% if @structure.association_detail.supporters_amount != 0 %>
				  		<li class="list-group-item"><b>Nombre d'adhérents</b> : <%= @structure.association_detail.supporters_amount %></li>
				  		<% end %>
				  		<% if @structure.association_detail.object != "" %>
				  		<li class="list-group-item"><b>Objet de l'association</b> : <%= break_the_lines(@structure.association_detail.object) %></li>
				  		<% end %>
				  	</ul>
				</div>
				<% end %>

				<div id="mapid" class="card" style="height: 500px; margin-top: 30px">
				 </div>

				 <%= link_to "mailto:contact@mlav.land" do %>
					<p class="float-right small" style="margin-top: 30px"><i class="fas fa-envelope"></i> Pour toute réclamation ou information, veuillez nous contacter en cliquant ici</p>
					<% end %>
					<br>

			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
	var mymap = L.map('mapid').setView([<%= @structure.lat.to_s + ", " + @structure.lng.to_s %>], 14);
	var marker = L.marker([<%= @structure.lat.to_s + ", " + @structure.lng.to_s %>]).addTo(mymap);

	marker.bindPopup("<b><%= @structure.name %></b><br/><%= @structure.full_address %>").openPopup();

  L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token={accessToken}', {
	attribution: '© <a href="https://www.mapbox.com/about/maps/">Mapbox</a> © <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>',
	tileSize: 512,
	maxZoom: 18,
	zoomOffset: -1,
	id: 'mapbox/light-v10',
	accessToken: 'pk.eyJ1IjoiYXZuZDI2IiwiYSI6ImNqdXUwamMwNTBjcDA0YW52ODM1Nnp5OW4ifQ.X2B60gqbpNhbYZvIkhsZRg'
	}).addTo(mymap);
  </script>