config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'maps#global'
  resources :structures, only: [:index, :show]
  resources :references, only: [:index, :show]
  resources :individuals, only: [:index, :show]
  resources :projects, only: [:index, :show]
  get '/map_structures', to: 'structures#map'
  get '/map_projects', to: 'projects#map'
  get '/global_map', to: 'maps#global'
  resources :partners, only: [:index]
  get '/about', to: 'statics#about'

  namespace :admin do
	  resources :structures
	  resources :structure_types, only: [:create, :new, :edit, :update, :destroy]
	  resources :structure_classifications, only: [:new, :create, :edit, :update, :destroy]
	  resources :structure_relations, only: [:create, :new, :destroy]
	  resources :parent_child_relations, only: [:new, :create, :destroy]
	  resources :references
    resources :reference_classes, only: [:new, :create, :edit, :update, :destroy]
	  resources :individuals
    resources :partners, only: [:new, :create, :edit, :update, :destroy]
    resources :structure_partners, only: [:new, :create, :destroy]
    resources :projects
    resources :project_classes, only: [:new, :create, :edit, :update, :destroy]
    resources :project_project_classes, only: [:create, :destroy]
    resources :partner_projects, only: [:create, :destroy]
    resources :structure_projects, only: [:create, :destroy]
  end
end

app/models/project.rb
class Project < ApplicationRecord
	
	include Geokit::Geocoders

	after_create :get_lat_lng

	has_many :project_project_classes
	has_many :project_classes, through: :project_project_classes

	has_many :partner_projects
	has_many :partners, through: :partner_projects

	has_many :structure_projects
	has_many :structures, through: :structure_projects

	enum status: {executed: "0", ongoing: "1", upcoming: "2"}

	acts_as_mappable :default_units => :kms,
                   :default_formula => :sphere,
                   :distance_field_name => :distance,
                   :lat_column_name => :lat,
                   :lng_column_name => :lng

  def status_fr
		if self.status == "executed"
			return "Réalisé"
		elsif self.status == "ongoing"
			return "En cours"
		else
			return "À venir"
		end
	end

	def structures_array
		structures = []
		self.structures.each do |structure|
			structures << structure.name
		end
		return structures
	end

  def get_lat_lng
		full_address = self.address + ", " + self.zip_code + ", " +  self.city + ", " + self.country
		loc = Geokit::Geocoders::GoogleGeocoder.geocode(full_address)
		if loc.success
			self.update(lat: loc.lat, lng: loc.lng)
		end
	end

	def full_address
		if self.address != "" && self.zip_code != "" && self.city != "" && self.country != ""
			return self.address + ", " + self.zip_code + ", " +  self.city + ", " + self.country
		elsif self.address == "" && self.zip_code != "" && self.city != "" && self.country != ""
			return self.zip_code + ", " +  self.city + ", " + self.country
		elsif self.address == "" && self.zip_code == "" && self.city != "" && self.country != ""
			return self.city + ", " + self.country
		elsif self.address == "" && self.zip_code == "" && self.city == "" && self.country != ""
			return self.country
		end
	end

end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < ApplicationController
	before_action :set_variables
	before_action :is_admin, only: [:new, :create, :edit, :update, :destroy]

	def index
		@projects = Project.all.order("title ASC")
	end

	def show
		@project = Project.find(params[:id])
	end

	def new
	end

	def create
		project = Project.create(title: params[:title], description: params[:description], website: "http://" + params[:website], status: params[:status], year: params[:year], address: params[:address], zip_code: params[:zip_code], city: params[:city], country: params[:country], notes: params[:notes])
		ProjectProjectClass.create(project: project, project_class_id: params[:project_class_id])
		StructureProject.create(structure_id: params[:structure_id], project: project)
		if params[:second_structure] == "1"
			StructureProject.create(structure_id: params[:second_structure_id], project: project)
		end
		if params[:second_class] == "1"
			ProjectProjectClass.create(project: project, project_class_id: params[:second_project_class_id])
		end
		if params[:third_class] == "1"
			ProjectProjectClass.create(project: project, project_class_id: params[:third_project_class_id])
		end
		if params[:add_partner] == "1"
			PartnerProject.create(project: project, partner_id: params[:partner_id])
		end
		if params[:second_partner] == "1"
			PartnerProject.create(project: project, partner_id: params[:second_partner_id])
		end
		redirect_to admin_project_path(project.id)
	end

	def edit
		@project = Project.find(params[:id])
	end

	def update
		project = Project.find(params[:id])
		if params[:status] == "3"
			project.update(title: params[:title], description: params[:description], website: "http://" + params[:website], year: params[:year], address: params[:address], zip_code: params[:zip_code], city: params[:city], country: params[:country], notes: params[:notes])
		else
			project.update(title: params[:title], description: params[:description], website: "http://" + params[:website], status: params[:status], year: params[:year], address: params[:address], zip_code: params[:zip_code], city: params[:city], country: params[:country], notes: params[:notes])
		end
		project.get_lat_lng
		redirect_to admin_project_path(project.id)
	end

	def destroy
		project = Project.find(params[:id])
		project.destroy
		redirect_to admin_projects_path
	end

	private

  def set_variables
    @project_classes = []
    ProjectClass.all.order("name ASC").each do |project_class|
      @project_classes << [project_class.name, project_class.id]
    end

    @partners = []
    Partner.all.order("name ASC").each do |partner|
      @partners << [partner.name, partner.id]
    end

    @structures = []
    Structure.all.order("name ASC").each do |structure|
    	@structures << [structure.name, structure.id]
    end
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_variables

	def index
    @projects_count = Project.all.count

    @project_classes.insert(0, ["Tous les classifications de projets", 0])

    case 
      when params[:search] == nil && params[:project_class_id] == nil
        @projects = Project.all.order("title ASC")

      when (params[:search] == "" || params[:search] == " " || params[:search] == nil) && params[:project_class_id] == "0"
        @projects = Project.all.order("title ASC")

      when (params[:search] != "" || params[:search] != " ") && params[:project_class_id] == "0"
        @projects = Project.where('lower(title) LIKE ?', "%#{params[:search].downcase}%") + Project.where('lower(city) LIKE ?', "%#{params[:search].downcase}%")

      when (params[:search] == "" || params[:search] == " " || params[:search] == nil) && params[:project_class_id] != "0"
        @projects = []
        Project.all.each do |project|
          project.project_classes.each do |project_class|
            if project_class.id == params[:project_class_id].to_i
              @projects << project
            end
          end
        end

      when (params[:search] != "" || params[:search] != " " || params[:search] != nil) && params[:project_class_id] != nil
        @projects_search = Project.where('lower(title) LIKE ?', "%#{params[:search].downcase}%") + Project.where('lower(city) LIKE ?', "%#{params[:search].downcase}%")
        @projects = []
        @projects_search.each do |project|
          project.project_classes.each do |project_class|
            if project_class.id == params[:project_class_id].to_i
              @projects << project
            end
          end
        end

      else
        @projects = Project.all.order("title ASC")
    end

    if params[:project_class_id].to_i != 0
      @project_class = ProjectClass.find(params[:project_class_id].to_i)
      @selected_project_class = [@project_class.name, @project_class.id]
    end
    
	end

	def show
		@project = Project.find(params[:id])
	end

	def map
  	@projects = Project.all.order("title ASC")
  end

  private

  def set_variables
    @project_classes = []
    ProjectClass.all.each do |project_class|
      @project_classes << [project_class.name, project_class.id]
    end
  end

end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/admin/projects/edit.html.erb
<div class="container">
	<div class="row justify-content-center">
		<div class="col-lg-8">

			<%= link_to project_path(@project.id) do %>
			<i class="fas fa-arrow-left"></i> Retour à la page projet
			<% end %><br><br>
			<hr>

			<h2>Editer les structures porteuses du projet</h2>
			<br>

			<p>Structures porteuses du projet</p>
			<div class="card" style="margin-top: -5px; margin-bottom: 20px">
				<ul class="list-group list-group-flush">
					<% @project.structure_projects.each do |structure_project| %>
					<li class="list-group-item align-items-center">
						<span class="float-left"><%= structure_project.structure.name %></span>
						<span class="float-right"><%= link_to "X", admin_structure_project_path(structure_project.id), :class => "btn btn-danger btn-sm", data: { confirm: "Êtes-vous sûr(e) de vouloir continuer cette action ?" }, :method => "delete" %></span>
					</li>
					<% end %>
				</ul>
			</div>

			<%= form_tag admin_structure_projects_path, :method => :post do %>

			<div class="form-group">
			<%= label_tag 'Ajouter une structure porteuse du projet' %>
			<%= select_tag(:structure_id, options_for_select(@structures), {:class => "form-control"}) %>
			</div>
			<br>

			<%= hidden_field_tag :project_id, @project.id %>

			<%= submit_tag "Ajouter une structure porteuse du projet", :class => "btn btn-lg btn-sm btn-block btn-success" %>
			<% end %>
			<br>

			<hr>

			<h2>Editer la classification du projet</h2>
			<br>

			<p>Classifications du projet</p>
			<div class="card" style="margin-top: -5px; margin-bottom: 20px">
				<ul class="list-group list-group-flush">
					<% @project.project_project_classes.each do |project_project_class| %>
					<li class="list-group-item align-items-center">
						<span class="float-left"><%= project_project_class.project_class.name %></span>
						<span class="float-right"><%= link_to "X", admin_project_project_class_path(project_project_class.id), :class => "btn btn-danger btn-sm", data: { confirm: "Êtes-vous sûr(e) de vouloir continuer cette action ?" }, :method => "delete" %></span>
					</li>
					<% end %>
				</ul>
			</div>

			<%= form_tag admin_project_project_classes_path, :method => :post do %>

			<div class="form-group">
			<%= label_tag 'Ajouter classification de projet supplémentaire' %>
			<%= select_tag(:project_class_id, options_for_select(@project_classes), {:class => "form-control"}) %>
			</div>
			<br>

			<%= hidden_field_tag :project_id, @project.id %>

			<%= submit_tag "Ajouter classification de projet supplémentaire", :class => "btn btn-lg btn-sm btn-block btn-success" %>
			<% end %>
			<br>

			<hr>

			<h2>Editer les partenaires du projet</h2>
			<br>

			<p>Partenaires du projet</p>
			<div class="card" style="margin-top: -5px; margin-bottom: 20px">
				<ul class="list-group list-group-flush">
					<% @project.partner_projects.each do |partner_project| %>
					<li class="list-group-item align-items-center">
						<span class="float-left"><%= partner_project.partner.name %></span>
						<span class="float-right"><%= link_to "X", admin_partner_project_path(partner_project.id), :class => "btn btn-danger btn-sm", data: { confirm: "Êtes-vous sûr(e) de vouloir continuer cette action ?" }, :method => "delete" %></span>
					</li>
					<% end %>
				</ul>
			</div>

			<%= form_tag admin_partner_projects_path, :method => :post do %>

			<div class="form-group">
			<%= label_tag 'Ajouter un partenaire de projet supplémentaire' %>
			<%= select_tag(:partner_id, options_for_select(@partners), {:class => "form-control"}) %>
			</div>
			<br>

			<%= hidden_field_tag :project_id, @project.id %>

			<%= submit_tag "Ajouter classification de projet supplémentaire", :class => "btn btn-lg btn-sm btn-block btn-success" %>
			<% end %>
			<br>

			<hr>

			<h2>Editer les informations du projet</h2>
			<br>

			<%= form_tag url_for(action: 'update'), method: "put" do %>


			<div class="form-group">
			<%= label_tag 'Titre du projet' %>
			<%= text_field_tag 'title', @project.title, :class => "form-control" %>
			</div>

			<div class="form-group">
			<%= label_tag 'Description' %>
			<%= text_area_tag 'description', @project.description, :class => "form-control", :rows => "4" %>
			</div>

			<div class="form-group">
			<%= label_tag 'Site Internet' %>
			<div class="input-group mb-2">
				<div class="input-group-prepend">
	          		<div class="input-group-text">http://</div>
	        	</div>
				<%= text_field_tag 'website', @project.website[7..-1], :class => "form-control" %>
			</div>
			</div>

			<div class="form-group">
				<%= label_tag 'Année' %>
				<%= text_field_tag 'year', @project.year, :class => "form-control integeronly" %> 
			</div>

			<div class="form-group">
			  <%= label_tag 'Statut du projet' %>
				<%= select_tag(:status, options_for_select([["Choix", "3"], ['Réalisé', "0"], ['En cours', "1"], ['À venir', "2"]]), {:class => "form-control"}) %>
			</div>

			<hr>

			<div class="form-group">
			<%= label_tag 'Adresse' %>
			<%= text_field_tag 'address', @project.address, :class => "form-control" %>
			</div>

			<div class="row form-group">
			    <div class="col">
			      	<%= label_tag 'Code postal' %>
					<%= text_field_tag 'zip_code', @project.zip_code, :class => "form-control integeronly" %> 
			    </div>
			   
			    <div class="col">
			      	<%= label_tag 'Ville' %>
					<%= text_field_tag 'city', @project.city, :class => "form-control" %>
			    </div>
			</div>
			<div class="form-group">
			      	<%= label_tag 'Pays' %>
					<%= text_field_tag 'country', @project.country, :class => "form-control" %>
			</div>

			<hr>

			<div class="form-group">
			<%= label_tag 'Notes' %>
			<%= text_area_tag 'notes', @project.notes, :class => "form-control", :rows => "4" %>
			</div>

			<br>
			<%= submit_tag "Editer le projet", :class => "btn btn-lg btn-sm btn-block btn-success" %>
			<br><br>
			<% end %>

		</div>
	</div>
</div>

app/views/admin/projects/index.html.erb
<div class="container">
	<div class="row justify-content-center">
		<div class="col-lg-8" style="margin-bottom: 5vh">

			<h2>Projets (<span class="count"><%= @projects.count %></span>)</h2><br>

			<div id="mapid" class="card" style="height: 600px">
			 </div>

			<div class="card" style="margin-top: 30px">
			  <ul class="list-group list-group-flush">
			  	<% @projects.each do |project| %>
					<li class="list-group-item align-items-center">
						<i class="fas fa-home"></i>
						<%= link_to project.title, admin_project_path(project.id) %>
						<br/><span class="small">de <%= project.structures_array.join(", ") %> | <%= project.city %> | <%= project.status_fr %></span>
						<span class="float-right small"><%= project.year %></span>
					</li>
				<% end %>
			  </ul>
			</div>
			
		</div>
	</div>
</div>


<script type="text/javascript">
	$('.count').each(function () {
        $(this).prop('Counter',0).animate({
            Counter: $(this).text()
        }, {
            duration: 4000,
            easing: 'swing',
            step: function (now) {
                $(this).text(Math.ceil(now));
            }
        });
    });
    
	var map = L.map('mapid').setView([46.803178243429265,2.735502332685428], 6);
	L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token={accessToken}', {
	attribution: '© <a href="https://www.mapbox.com/about/maps/">Mapbox</a> © <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>',
	tileSize: 512,
	maxZoom: 18,
	zoomOffset: -1,
	id: 'mapbox/light-v10',
	accessToken: 'pk.eyJ1IjoiYXZuZDI2IiwiYSI6ImNqdXUwamMwNTBjcDA0YW52ODM1Nnp5OW4ifQ.X2B60gqbpNhbYZvIkhsZRg'
	}).addTo(map);

	<% @projects.each do |project| %>

		var <%= "marker" + project.id.to_s %> = L.marker([<%= project.lat.to_s + ", " + project.lng.to_s %>]).addTo(mymap);

		var <%= "container" + project.id.to_s %> = $('<div />');

		<%= "container" + project.id.to_s %>.on('click', '.smallPolygonLink', function() {});

		<%= "container" + project.id.to_s %>.html("<a href='<%= project_path(project.id) %>' class='smallPolygonLink'><%= project.title %></a><br/>");
		<%= "container" + project.id.to_s %>.append($('<span class="bold">').text(" <%= project.city %> "))

		<%= "marker" + project.id.to_s %>.bindPopup(<%= "container" + project.id.to_s %>[0]);
	<% end %>

  </script>

app/views/admin/projects/new.html.erb
<div class="container">
	<div class="row justify-content-center">
		<div class="col-lg-8">

			<h2>Ajouter un nouveau projet</h2>
			<br>

			<%= form_tag url_for(action: 'create'), method: "post" do %>


			<div class="form-group">
			<%= label_tag 'Titre du projet' %>
			<%= text_field_tag 'title', "", :placeholder => "Titre du projet", :class => "form-control" %>
			</div>

			<div class="form-group">
				<%= label_tag "Structure à l'origine du projet" %>
				<%= select_tag(:structure_id, options_for_select(@structures), {:class => "form-control"}) %>
			</div>

			<%= check_box_tag 'second_structure' %>
			<small><%= label_tag "Ajouter une seconde structure au projet" %></small>
				<br>

				<div class="second_structure" id="secondstructure">
					<div class="form-group">
						<%= label_tag "Seconde structure à l'origine du projet" %>
						<%= select_tag(:second_structure_id, options_for_select(@structures), {:class => "form-control"}) %>
					</div>
				</div>

			<hr>

			<div class="form-group">
			<%= label_tag 'Classification de projet' %>
			<%= select_tag(:project_class_id, options_for_select(@project_classes), {:class => "form-control"}) %>
			</div>

			<%= check_box_tag 'second_class' %>
			<small><%= label_tag "Ajouter une seconde classification" %></small>
			<br>

			<div class="second_class" id="secondclass">
				<div class="form-group">
					<%= label_tag 'Seconde classification de projet' %>
					<%= select_tag(:second_project_class_id, options_for_select(@project_classes), {:class => "form-control"}) %>
				</div>

				<%= check_box_tag 'third_class' %>
				<small><%= label_tag "Ajouter une troisième classification" %></small>
				<br>

				<div class="third_class" id="thirdclass">
					<div class="form-group">
						<%= label_tag 'Troisième classification de projet' %>
						<%= select_tag(:third_project_class_id, options_for_select(@project_classes), {:class => "form-control"}) %>
					</div>
				</div>

			</div>

			<hr>
			<%= check_box_tag 'add_partner' %>
			<small><%= label_tag "Ajouter un partenaire" %></small>

			<div class="add_partner" id="addpartner">
				<div class="form-group">
				<%= label_tag 'Partenaire du projet' %>
				<%= select_tag(:partner_id, options_for_select(@partners), {:class => "form-control"}) %>
				</div>

				<%= check_box_tag 'second_partner' %>
				<small><%= label_tag "Ajouter un second partenaire" %></small>

				<div class="second_partner" id="secondpartner">
					<div class="form-group">
					<%= label_tag 'Second partenaire du projet' %>
					<%= select_tag(:second_partner_id, options_for_select(@partners), {:class => "form-control"}) %>
					</div>
				</div>		

			</div>
			<hr>

			<div class="form-group">
			<%= label_tag 'Description' %>
			<%= text_area_tag 'description', "", :placeholder =>"Description du projet", :class => "form-control", :rows => "4" %>
			</div>

			<div class="form-group">
			<%= label_tag 'Site Internet' %>
			<div class="input-group mb-2">
				<div class="input-group-prepend">
	          		<div class="input-group-text">http://</div>
	        	</div>
				<%= text_field_tag 'website', "", :placeholder => "url.domaine", :class => "form-control" %>
			</div>
			</div>

			<div class="form-group">
				<%= label_tag 'Année' %>
				<%= text_field_tag 'year', "", :placeholder => "Année", :class => "form-control integeronly" %> 
			</div>

			<div class="form-group">
			  <%= label_tag 'Statut du projet' %>
				<%= select_tag(:status, options_for_select([['Réalisé', "0"], ['En cours', "1"], ['À venir', "2"]]), {:class => "form-control"}) %>
			</div>

			<hr>

			<div class="form-group">
			<%= label_tag 'Adresse' %>
			<%= text_field_tag 'address', "", :placeholder => "Numéro de rue et nom de rue", :class => "form-control" %>
			</div>

			<div class="row form-group">
			    <div class="col">
			      	<%= label_tag 'Code postal' %>
					<%= text_field_tag 'zip_code', "", :placeholder => "Code postal", :class => "form-control integeronly" %> 
			    </div>
			   
			    <div class="col">
			      	<%= label_tag 'Ville' %>
					<%= text_field_tag 'city', "", :placeholder => "Nom de la ville", :class => "form-control" %>
			    </div>
			</div>
			<div class="form-group">
			      	<%= label_tag 'Pays' %>
					<%= text_field_tag 'country', "", :placeholder => "Pays", :class => "form-control" %>
			</div>

			<hr>

			<div class="form-group">
			<%= label_tag 'Notes' %>
			<%= text_area_tag 'notes', "", :placeholder =>"Notes supplémentaires", :class => "form-control", :rows => "4" %>
			</div>

			<br>
			<%= submit_tag "Créer un nouveau projet", :class => "btn btn-lg btn-sm btn-block btn-success" %>
			<br><br>
			<% end %>

		</div>
	</div>
</div>

app/views/admin/projects/show.html.erb
<div class="container">
	<div class="row justify-content-center">
		<div class="col-lg-8" style="margin-bottom: 5vh">

			<div class="card">
			  <div class="card-body">
			    <h2 class="card-title"><b><%= @project.title %></b></h2>
			    <h5>Un projet de
			    	<% k = 1 %>
			    	<% @project.structures.each do |structure| %>
			    	<%= link_to structure.name, structure_path(structure.id) %><% if @project.structures.count > 1 && k != @project.structures.count %>, <% end %>
			    	<% k += 1 %>
			    	<% end %>
			    </h5>
					<span class="badge badge-light"><%= @project.status_fr %></span><br/>
					<% @project.project_classes.each do |project_class| %>
					<span class="badge badge-info"><%= project_class.name %></span> 
					<% end %>
					<% if @project.year != nil %>
			   		<span class="float-right"><b>Année de livraison</b> : <%= @project.year %></span>
			   	<% end %>
			  </div>

			  <ul class="list-group list-group-flush">
			  	<li class="list-group-item"><b>Description</b> : 
			  		<% if @project.description != "" %>
			  		<%= break_the_lines(@project.description) %>
			  		<% else %>
			  		<i>non informée</i>
			  		<% end %>
			  	</li>
			  	<% if @project.address != "" %>
			    <li class="list-group-item"><b>Adresse</b> : <%= @project.full_address %></li>
			    <% end %>

			    <li class="list-group-item"><b>Site internet</b> : 
			    	<% if @project.website != "http://" %>
			    	<a href="<%= @project.website %>"><%= @project.website %></a>
			    	<% else %>
			    	<i>non informé</i>
			    	<% end %>
			    </li>
			    
			    <% if @project.partners != [] %>
			    	<li class="list-group-item">
				    	<% if @project.partners.count == 1 %>
				    	<b>Partenaire du projet</b> :
				    	<% else %>
				    	<b>Partenaires du projet</b> :
				    	<% end %>
				    		<% i = 1 %>
				    		<% @project.partners.each do |partner| %>
				    			<%= link_to partner.name, partner.website, target: "_blank" %><% if @project.partners.count > 1 && i != @project.partners.count %>, <% end %>
				    			<% i += 1 %>
				    		<% end %>
				    </li>
			    <% end %>
			    
			  </ul>
			</div>


			<div id="mapid" class="card" style="height: 500px; margin-top: 30px">
			 </div>


			<% if user_signed_in? && current_user.admin == true %>

			<% if @project.notes != "" %>
			<div class="card" style="margin-top: 30px">
				<div class="card-body">
					<h5 class="card-title">Notes</h5>
					<p><%= break_the_lines(@project.notes) %></p>
				</div>
			</div>
			<% end %>

			<div class="float-right" style="margin-top: 30px">
				<%= link_to "Éditer", edit_admin_project_path(@project.id), :class => "btn btn-warning" %> &nbsp;
				<%= link_to "Supprimer", admin_project_path(@project.id), :class => "btn btn-danger", data: { confirm: "Êtes-vous sûr(e) ?" }, :method => "delete" %>
			</div>

			<% end %>

		</div>
	</div>
</div>

<script type="text/javascript">
	var mymap = L.map('mapid').setView([<%= @project.lat.to_s + ", " + @project.lng.to_s %>], 14);
	var marker = L.marker([<%= @project.lat.to_s + ", " + @project.lng.to_s %>]).addTo(mymap);

	marker.bindPopup("<b><%= @project.title %></b><br/><%= @project.full_address %>").openPopup();

  L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token={accessToken}', {
	attribution: '© <a href="https://www.mapbox.com/about/maps/">Mapbox</a> © <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>',
	tileSize: 512,
	maxZoom: 18,
	zoomOffset: -1,
	id: 'mapbox/light-v10',
	accessToken: 'pk.eyJ1IjoiYXZuZDI2IiwiYSI6ImNqdXUwamMwNTBjcDA0YW52ODM1Nnp5OW4ifQ.X2B60gqbpNhbYZvIkhsZRg'
	}).addTo(mymap);
  </script>